import numpy as np
import pandas as pd
from matplotlib import pyplot as plt, text
from pathlib import Path
from shutil import copy
import subprocess
import os
import re
import pyARCiS
import shutil



def format_value(value):
    if isinstance(value, bool):
        return ".true." if value else ".false."
    if isinstance(value, float):
        return f"{value:.12g}".replace("e", "d")
    if isinstance(value, str):
        if value.startswith(("'", '"')):
            return value
        return f"'{value}'"
    return str(value)




class ArcisWrapper:
    def __init__(self, input_file = None, output_path = None, src_path = None):
        self.input_file = input_file
        self.output_path = output_path
        self.src_path = src_path

        #check if the input file exists already
        if self.input_file is not None:
            if not Path(self.input_file).exists() :
                print(f"Warning: Input file {self.input_file} does not exist. Let's just copy over the default one wrapper_test.dat.")
                source = Path('./src/Example/wrapper_test.dat')
                target = Path(self.input_file)
                copy(source, target)

        #check if the output path exisits already, if not create it
        if self.output_path is not None:        
            if not Path(self.output_path).exists():
                print(f"Output path {self.output_path} does not exist. Creating it.")
                Path(self.output_path).mkdir(parents=True, exist_ok=True)
        
        if self.src_path is None:
            self.src_path = '/Users/louissiebenaler/ARCiS/src/'

        # This is just list[str]
        if self.input_file is not None:
            self.input_lines = Path(self.input_file).read_text().splitlines()

        
        pass
    
    
    def set(self, key, value):
        ''' This function allows you to set flags in the Arcis input file. It will search for the flag and relace the vlue. If it does not find the flag it will add it to the end of the file'''
        value = format_value(value)

        for i, line in enumerate(self.input_lines):
            body, *comment = line.split("!", 1)

            if "=" not in body:
                continue

            lhs, rhs = body.split("=", 1)

            if lhs.strip().lower() == key.lower():
                new_line = f"{lhs.strip()}={value}"

                if comment:
                    new_line += " !" + comment[0]

                self.input_lines[i] = new_line
                return self

        # If key was not found, append it
        self.input_lines.append(f"{key}={value}")
        return self


    def write_input(self):
        text = "\n".join(self.input_lines) + "\n"

        Path(self.input_file).write_text(text)
        return self.input_file




    def run_arcis(self):
        '''This functions lets you execute Arcis'''
        cmd = [self.src_path + 'ARCiS', self.input_file, '-o', self.output_path]

        env = os.environ.copy()
        env["DYLD_LIBRARY_PATH"] = (
            "/Users/louissiebenaler/ARCiS/MultiNest/lib:"
            + env.get("DYLD_LIBRARY_PATH", "")
        )

        subprocess.run(cmd, check = True, env = env)
        


    def plot_tp_profile(self, output_path = None, show = False, label = '', color = 'black', ls = '-'):
        ''' This function plots the TP profile that is generated by Arcis'''
        if output_path is None:
            output_path = self.output_path
        tp = np.loadtxt(output_path + 'mixingratios.dat', skiprows = 1)
        conv =  pd.read_csv(output_path +  "convection.dat", sep=r"\s+", names=["T", "P_bar", "T_ad_ref"], na_values=["NaN"])
        mask = conv["T"].notna()
        if label != '':
            plt.plot(tp[:, 0], tp[:, 1], color = color, ls = ls, label = label)
            plt.scatter(tp[mask, 0], tp[mask, 1], color=color, alpha=0.3)
        else:
            plt.plot(tp[:, 0], tp[:, 1], color = color, ls = ls)
            plt.scatter(tp[mask, 0], tp[mask, 1], color=color, alpha=0.3)

        if show:
            plt.yscale('log')
            plt.xlabel('Temperature (K)')
            plt.ylabel('Pressure (bar)')
            plt.legend(frameon = False)
            plt.gca().invert_yaxis()
            plt.show()

        pass

    
    def plot_gas_mixing_ratios(self, output_path = None, specie = None, show = False, label = '', color = 'black', ls = '-'):
        ''' This function plots the gas mixing ratios that are generated by Arcis. It plots either the total gas density or the gas mixing ratio of a specific specie as function of pressure'''
        if output_path is None:
            output_path = self.output_path
        file = 'mixingratios.dat'

        #need to do this because there is an annoying # in the header (I don't get why people add this lol)
        with open(output_path + file, "r") as f:
            header = f.readline().lstrip("#").split()
        header = [header[0] + header[1], header[2] + header[3], *header[4:]]
        print(header)
        #Read the data
        df = pd.read_csv(output_path + file, sep=r"\s+", comment="#",  header=None, names=header)
        print('Check', df)



        if specie is not None and specie in df.columns:
            plt.plot(df[specie], df['P[bar]'], color = color, ls = ls, label = specie)
        else:
            print(f'Either you did not specify a specie or the specie {specie} does not exist in the header. Too bad...')
        if show:
            plt.yscale('log')
            plt.xscale('log')
            plt.xlabel('Mixing ratio or density')
            plt.ylabel('Pressure (bar)')
            plt.xlim(1e-25, 1)
            plt.legend(frameon = False)
            plt.gca().invert_yaxis()
            plt.show()

        pass

    

    def plot_cloud_mixing_ratios(self, output_path = None, specie = None, show = False, label = '', color = 'black', ls = '-'):
        ''' This function plots the cloud densities/or mixing ratios that are generated by Arcis. It plots either the total cloud density or the cloud mixing ratio of a specific specie as function of pressure'''
        if specie is None:
            file = 'clouddens01.dat'
            header = []
            df = pd.read_csv(output_path + file, sep=r"\s+", comment="#", header=None, names=["P[bar]", "dens[g/cm3]", "eq_dens", "gas_dens"])
        else:
            file = 'cloudstructure0010.dat'
             #need to do this because there is an annoying # in the header (I don't get why people add this lol)
            with open(output_path + file, "r") as f:
                header = f.readline().lstrip("#").split()
            #Read the data
            df = pd.read_csv(output_path + file, sep=r"\s+", comment="#", header=None, names=header)

        

        #check with species are present in the atmosphere
        for s in header[3:-4]:
            if s[-3:] == '[s]':
                idx = np.where(df[s] > 1e-30)[0]
                if len(idx) > 0:
                    print(f'The specie {s} is present in the atmosphere between {df["P[bar]"].iloc[idx[-1]]} bar and {df["P[bar]"].iloc[idx[0]]} bar')
        
        
        if specie is not None and specie in header:
            print(f'Good the specie {specie} is in the header, I can plot this')
            #print('Other options for species would be:', header)
            plt.plot(df[specie], df['P[bar]'], color = color, ls = ls, label = specie)
        else:
            print(f'Either you did not specify a specie or the specie {specie} does not exist in the header. Either way I will show you the total cloud density')
            plt.plot(df['dens[g/cm3]'], df['P[bar]'], color = color, ls = ls, label ='Total cloud density for ' + label)
        
        if show:
            plt.yscale('log')
            plt.xscale('log')
            plt.xlabel('Mixing ratio or density')
            plt.ylabel('Pressure (bar)')
            plt.xlim(1e-25, 1)
            plt.legend(frameon = False)
            plt.gca().invert_yaxis()
            plt.show()

        pass



        



    def get_Teq(self, output_path = None, bond_albedo = None):
         ''' This function determines the equilibrium temperature of the planet based on the Arcis output (assuming an Albedo of zero for now)'''
         if output_path is None:
            print('No output path specified, using the default output path')
            output_path = self.output_path
        
         sigma = 5.670374419e-8  # W m^-2 K^-4

         if bond_albedo is None:
             log_file = Path(output_path + '/log.dat')
             text = log_file.read_text()
             matches = re.findall(r"Day-side albedo:\s*([0-9.eE+-]+)", text)
             if not matches:
                raise ValueError(f"No albedo found in {log_file}")
             bond_albedo = float(matches[-1])  # final value, if several iterations exist
             print(f"Bond albedo: {bond_albedo}")


         data = np.loadtxt(output_path +  '/irradiation')
         wavelength_um = data[:, 0]
         irradiance = data[:, 1]  # W m^-2 micron^-1

         order = np.argsort(wavelength_um)
         f_inc = np.trapz(irradiance[order], wavelength_um[order])
         print(f"Incident flux: {f_inc} W/m^2") #tot flux at the stellar surface is 55299108.536605276 W m^-2 (to convert to cgs units, multiply by 1e3)
         print(55299108.536605276 * (0.00465047 / 1)**2)

         teq = ((1.0 - bond_albedo) * f_inc / (4.0 * sigma))**0.25
         teq2 = 5777 * np.sqrt(0.00465047/ (2 * 1)) * (1 - bond_albedo)**0.25

         return teq, teq2


    def define_radius(self, Mp, logg):
        ''' This function defines the radius of the planet based on the mass (given in Jupiter masses) and logg (given in log10(g) in cgs). It returns the radius in Jupiter radii'''
        g = 10**logg
        Mjup = 1.89816e30 # g
        Rjup = 7.1492e9 # cm
        G = 6.67430e-8 # cm^3 g^-1 s
        R = np.sqrt(G * Mp * Mjup / g) / Rjup
        return R


    def check_convergence(self, output_path = None, iterations = None):
        ''' This function checks if the Arcis run has converged based on the log.dat file. It returns True if the run has converged and False if it has not.'''
        if output_path is None:
            output_path = self.output_path
        log_file = Path(output_path + '/log.dat')
        text = log_file.read_text()
        matches = re.findall(r"Converged:\s*(True|False)", text)
        if not matches:
            raise ValueError(f"No convergence information found in {log_file}")
        converged = matches[-1] == "True"  # final value, if several iterations exist
        return converged



    def tp_sanity(self, output_path = None, plot = False):
        ''' This function checks if the temperature profile is reasonable '''
        #we need to check wether there are no temperature inversions anymore below the radiative convective boundary. We can do this by checking if the temperature is monotonically decreasing with pressure below the RCB. If it is not, we can print a warning message and plot the temperature profile.
        if output_path is None:
            output_path = self.output_path

        tp = np.loadtxt(output_path + 'mixingratios.dat', skiprows = 1)
        conv =  pd.read_csv(output_path +  "convection.dat", sep=r"\s+", names=["T", "P_bar", "T_ad_ref"], na_values=["NaN"])
        mask = conv["T"].notna()

        #check if the temperature is monotonically decreasing with pressure below the RCB
        if not np.all(np.diff(tp[mask, 0]) <= 0):
            print(f"Warning: The temperature profile is not monotonically decreasing with pressure below the RCB in {output_path}. This could indicate a problem with the model.")
            if plot:
                plt.plot(tp[:, 0], tp[:, 1], color = 'black', ls = '-')
                plt.scatter(tp[mask, 0], tp[mask, 1], color='red', alpha=0.3)
                plt.yscale('log')
                plt.xlabel('Temperature (K)')
                plt.ylabel('Pressure (bar)')
                plt.gca().invert_yaxis()
                plt.title('File: ' + output_path)
                plt.show()


        




if __name__ == "__main__":
    print("Hello, World!")
    
    '''
    tint = 1000
    a = 5
    clouds = [True]
    Tint = 900
    Res = [10]

    for c in clouds:
        for res in Res:
            if c:
                #case = ArcisWrapper(input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_clouds.dat', output_path = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/Tint_{Tint}_clouds_specresLR{res}_1e-2/')
                case = ArcisWrapper(input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_clouds_Sonora_tmp.dat', output_path = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/test_clouds_Sonora_og/')
                case.set("cloud1:coverage", 1.0)
                case.set("condensates", False)
            else:
                case = ArcisWrapper(input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_gas.dat', output_path = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/test_gas_Sonora/')
                case.set("condensates", True)

            
            case.set("TeffP", Tint)
            case.set("specres_LR", res)
            case.set("Dplanet", 200)
            case.set("metallicity", 0.0)
            R = case.define_radius(1, 3.5)
            case.set("Rp", R)
            

            case.write_input()


            case.run_arcis()
        
    '''
    

    '''
    tint = 600
    a = 0.1
    #clouds = [True, False]
    clouds = [True]

    for c in clouds:
        if c:
            case = ArcisWrapper(input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_clouds.dat', output_path = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/Jupiter_clouds/')
            case.set("cloud1:coverage", 1.0)
            case.set("condensates", False)
        else:
            case = ArcisWrapper(input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_gas.dat', output_path = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/Jupiter_syoung_gas/')
            case.set("condensates", True)

        case.set("Mp", 1.0)       
        case.set("Rp", 1.0)
        case.set("computeT", True)
        case.set("TeffP", tint)
        case.set("useEOS", True)
        case.set("pmax", 100)
        case.set("Dplanet", a)

        case.write_input()


        case.run_arcis()
        '''
    
    '''
    tint = 600
    a = 0.5
    #clouds = [True, False]
    temperatures = [100.0, 200.0, 400.0, 600.0]

    for Tint in temperatures:
       
        case = ArcisWrapper(input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_clouds.dat', output_path = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/WJupiter_syoung_clouds_T{Tint}_test_test/')
        #case.set("cloud1:coverage", 1.0)
        #case.set("condensates", False)
       
        #case.set("cloud1:Kzz", K)
        #case.set("Mp", 1.0)       
        #case.set("Rp", 1.0)
        #case.set("computeT", True)
        case.set("TeffP", Tint)
        #case.set("useEOS", True)
        #case.set("pmax", 100)
        #case.set("Dplanet", a)

        case.write_input()


        case.run_arcis()
    '''
    



    
    #'''
    input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_clouds.dat'
    output_dir = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/test_pyArcis/'

    case = ArcisWrapper(input_file = input_file, output_path = output_dir)
    case.set("condensates", False)
    case.write_input()

    # Initialize once: opacity FITS files are read here.
    pyARCiS.pyinit(input_file, output_dir)
    pyARCiS.pyverbose(True)

    nlam = pyARCiS.pyex.nlam
    lam = np.empty(nlam)
    emis = np.empty(nlam)

    results_dir = Path("loop_results")
    results_dir.mkdir(exist_ok=True)

    D = [0.01, 0.05, 0.1, 0.2, 0.5, 1, 2]
    D = [0.5]

    for d in D:
        print('Doing D =', d)
       
        pyARCiS.pysetvalue("TeffP", 200)
        pyARCiS.pysetvalue("metallicity", 0.5)
        #R = case.define_radius(1, logg)
        #pyARCiS.pysetvalue("Rp", R)

        pyARCiS.pysetvalue("Dplanet", d)
        #pyARCiS.pysetkeyword("condensates", ".True.")
    


        # Recalculate the model using the in-memory opacity tables.
        pyARCiS.pycomputemodel()

        pyARCiS.pywritefiles()

        run_dir = Path('/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example') / f"clouds_convection_new_fixed"

        # Avoid accidentally mixing old and new results.
        if run_dir.exists():
            raise FileExistsError(
                f"{run_dir} already exists; rename or remove it first."
            )

        # Save all files generated for this run.
        shutil.copytree(output_dir, run_dir)
    #'''
    
    

    '''
    #============================ 
    #now do gas only

    input_file = '/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/wrapper_test_gas.dat'
    output_dir = f'/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example/test_pyArcis/'

    case = ArcisWrapper(input_file = input_file, output_path = output_dir)
    case.set("condensates", True)
    case.write_input()

    # Initialize once: opacity FITS files are read here.
    pyARCiS.pyinit(input_file, output_dir)
    pyARCiS.pyverbose(True)

    nlam = pyARCiS.pyex.nlam
    lam = np.empty(nlam)
    emis = np.empty(nlam)

    results_dir = Path("loop_results")
    results_dir.mkdir(exist_ok=True)

    logG = [1.5, 3, 4, 5]
       
   
    for logg in logG:
        print('Doing logg =', logg)
        
        pyARCiS.pysetvalue("TeffP", 200)
        pyARCiS.pysetvalue("metallicity", 0.48)
        R = case.define_radius(1, logg)
        pyARCiS.pysetvalue("Rp", R)
        #pyARCiS.pysetkeyword("condensates", ".True.")
    


        # Recalculate the model using the in-memory opacity tables.
        pyARCiS.pycomputemodel()

        pyARCiS.pywritefiles()

        run_dir = Path('/Users/louissiebenaler/ARCiS/ARCIS_2026/src/Example') / f"g_{logg}_gas"

        # Avoid accidentally mixing old and new results.
        if run_dir.exists():
            raise FileExistsError(
                f"{run_dir} already exists; rename or remove it first."
            )

        # Save all files generated for this run.
        shutil.copytree(output_dir, run_dir)
    '''    







        
    