#!/usr/bin/env python3
"""Downsample an ARCiS correlated-k FITS table in wavelength.

The implementation follows the wavelength/g-distribution rebinning in
src/OpacityFITS.f: overlapping wavelength cells are pooled with their
wavelength-overlap and g-quadrature weights, sorted by opacity, and averaged
over a new g grid.

The input FITS image is memory-mapped and the output table is backed by a
temporary on-disk array, so the full input or output table is never held in
RAM.
"""

from __future__ import annotations

import argparse
import os
import tempfile
import time
from pathlib import Path

import numpy as np
from astropy.io import fits


def wavelength_edges(centres: np.ndarray) -> np.ndarray:
    """Return the logarithmic cell edges used by ARCiS."""
    centres = np.asarray(centres, dtype=np.float64)
    if centres.ndim != 1 or centres.size < 2:
        raise ValueError("The wavelength grid must contain at least two points")
    if np.any(~np.isfinite(centres)) or np.any(np.diff(centres) <= 0.0):
        raise ValueError("The wavelength grid must be finite and increasing")

    edges = np.empty(centres.size + 1, dtype=np.float64)
    edges[1:-1] = np.sqrt(centres[:-1] * centres[1:])
    edges[0] = centres[0] ** 2 / edges[1]
    edges[-1] = centres[-1] ** 2 / edges[-2]
    return edges


def constant_resolution_grid(
    source_edges: np.ndarray, resolution: float
) -> tuple[np.ndarray, np.ndarray]:
    """Construct complete constant-R cells contained in the source range."""
    if not np.isfinite(resolution) or resolution <= 0.0:
        raise ValueError("resolution must be positive")

    ratio = 1.0 + 1.0 / resolution
    log_ratio = np.log(ratio)
    nbin = int(
        np.floor(
            np.log(source_edges[-1] / source_edges[0]) / log_ratio
            + 1.0e-12
        )
    )
    if nbin < 1:
        raise ValueError("The requested resolution produces no output bins")

    edges = source_edges[0] * np.exp(log_ratio * np.arange(nbin + 1))
    # Guard against a final edge just outside the source range due to rounding.
    while edges[-1] > source_edges[-1] * (1.0 + 5.0e-14):
        nbin -= 1
        edges = edges[:-1]
    centres = np.sqrt(edges[:-1] * edges[1:])
    return centres, edges


def gauss_legendre_weights(n: int) -> np.ndarray:
    """Gauss-Legendre weights on [0, 1], as generated by ARCiS gauleg."""
    if n < 1:
        raise ValueError("The number of g points must be at least one")
    _, weights = np.polynomial.legendre.leggauss(n)
    return np.asarray(weights / 2.0, dtype=np.float64)


def cumulative_integral_at(
    sorted_k: np.ndarray,
    sorted_weights: np.ndarray,
    quantiles: np.ndarray,
) -> np.ndarray:
    """Integrate a piecewise-constant sorted k distribution up to quantiles."""
    cumulative_weight = np.cumsum(sorted_weights, axis=1)
    cumulative_weight[:, -1] = 1.0
    cumulative_kw = np.cumsum(sorted_k * sorted_weights, axis=1)

    # First interval whose upper boundary is at or above each quantile.
    indices = np.sum(
        cumulative_weight[:, :, None] < quantiles[None, None, :], axis=1
    )
    indices = np.minimum(indices, sorted_k.shape[1] - 1)

    previous = np.maximum(indices - 1, 0)
    previous_weight = np.take_along_axis(
        cumulative_weight, previous, axis=1
    )
    previous_integral = np.take_along_axis(
        cumulative_kw, previous, axis=1
    )
    previous_weight = np.where(indices > 0, previous_weight, 0.0)
    previous_integral = np.where(indices > 0, previous_integral, 0.0)
    current_k = np.take_along_axis(sorted_k, indices, axis=1)

    return previous_integral + current_k * (
        quantiles[None, :] - previous_weight
    )


def rebin_k_distribution(
    values: np.ndarray,
    source_weights: np.ndarray,
    target_weights: np.ndarray,
) -> np.ndarray:
    """Re-sort and average k values over target g-probability intervals."""
    if values.ndim != 2:
        raise ValueError("values must have shape (number_of_rows, number_of_k_values)")

    weights = np.asarray(source_weights, dtype=np.float64)
    weights = weights / np.sum(weights)
    order = np.argsort(values, axis=1)
    sorted_k = np.take_along_axis(values, order, axis=1)
    sorted_weights = np.take_along_axis(
        np.broadcast_to(weights, values.shape), order, axis=1
    )

    target_weights = np.asarray(target_weights, dtype=np.float64)
    target_weights = target_weights / np.sum(target_weights)
    quantile_edges = np.concatenate(
        ([0.0], np.cumsum(target_weights))
    )
    quantile_edges[-1] = 1.0

    cumulative_integral = cumulative_integral_at(
        sorted_k, sorted_weights, quantile_edges
    )
    return np.diff(cumulative_integral, axis=1) / target_weights[None, :]


def extension_data(hdul: fits.HDUList, index: int) -> np.ndarray:
    if len(hdul) <= index or hdul[index].data is None:
        raise ValueError(f"Input table is missing required HDU {index}")
    return np.asarray(hdul[index].data, dtype=np.float64).reshape(-1)


def downsample(
    input_path: Path,
    output_path: Path,
    resolution: float,
    target_ng: int,
    overwrite: bool,
) -> None:
    if output_path.exists() and not overwrite:
        raise FileExistsError(
            f"{output_path} already exists; pass --overwrite to replace it"
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)

    temp_path: str | None = None
    start_time = time.monotonic()
    try:
        with fits.open(
            input_path,
            mode="readonly",
            memmap=True,
            do_not_scale_image_data=True,
        ) as hdul:
            source = hdul[0].data
            if source is None or source.ndim != 4:
                raise ValueError("HDU 0 must be a four-dimensional opacity array")

            temperatures = extension_data(hdul, 1)
            pressures = extension_data(hdul, 2)
            source_lam = extension_data(hdul, 3)

            # FITS NAXIS order is reversed in NumPy: (nP, nT, ng, nlam).
            n_pressure, n_temperature, source_ng, source_nlam = source.shape
            expected = (
                pressures.size,
                temperatures.size,
                source_ng,
                source_lam.size,
            )
            if source.shape != expected:
                raise ValueError(
                    f"HDU dimensions {source.shape} do not match the grid "
                    f"dimensions {expected}"
                )

            if len(hdul) > 4 and hdul[4].data is not None:
                source_g_weights = np.asarray(
                    hdul[4].data, dtype=np.float64
                ).reshape(-1)
                if source_g_weights.size != source_ng:
                    raise ValueError("HDU 4 does not contain ng source weights")
            else:
                source_g_weights = gauss_legendre_weights(source_ng)

            if target_ng == source_ng:
                target_g_weights = source_g_weights.copy()
            else:
                target_g_weights = gauss_legendre_weights(target_ng)

            source_edges = wavelength_edges(source_lam)
            target_lam, target_edges = constant_resolution_grid(
                source_edges, resolution
            )
            target_nlam = target_lam.size

            shape = (
                n_pressure,
                n_temperature,
                target_ng,
                target_nlam,
            )
            with tempfile.NamedTemporaryFile(
                prefix="arcis_ktable_",
                suffix=".bin",
                dir=output_path.parent,
                delete=False,
            ) as temporary:
                temp_path = temporary.name

            # Big-endian float64 is FITS-native and avoids a second full-size
            # byte-swapped copy when astropy writes the result.
            result = np.memmap(temp_path, mode="w+", dtype=">f8", shape=shape)
            n_rows = n_pressure * n_temperature

            print(
                f"Input:  nlam={source_nlam}, ng={source_ng}, "
                f"nT={n_temperature}, nP={n_pressure}"
            )
            print(
                f"Output: nlam={target_nlam}, ng={target_ng}, "
                f"R={resolution:g}"
            )

            for output_index in range(target_nlam):
                lower = target_edges[output_index]
                upper = target_edges[output_index + 1]

                first = max(
                    0,
                    int(np.searchsorted(source_edges, lower, side="right")) - 1,
                )
                stop = min(
                    source_nlam,
                    int(np.searchsorted(source_edges, upper, side="left")),
                )
                if stop <= first:
                    raise RuntimeError(
                        f"No source cells overlap output wavelength index {output_index}"
                    )

                cell_lower = source_edges[first:stop]
                cell_upper = source_edges[first + 1 : stop + 1]
                overlap = np.minimum(cell_upper, upper) - np.maximum(
                    cell_lower, lower
                )
                keep = overlap > 0.0
                overlap = overlap[keep]
                source_indices = np.arange(first, stop)[keep]

                # source block: (nP, nT, ng_source, n_wavelength_cells)
                block = np.asarray(
                    source[:, :, :, source_indices], dtype=np.float64
                )
                block = np.maximum(block, 0.0)
                # Pool wavelength first and g second, matching ww*wg in ARCiS.
                values = np.moveaxis(block, -1, -2).reshape(n_rows, -1)
                pooled_weights = (
                    overlap[:, None] * source_g_weights[None, :]
                ).reshape(-1)

                rebinned = rebin_k_distribution(
                    values, pooled_weights, target_g_weights
                )
                result[:, :, :, output_index] = rebinned.reshape(
                    n_pressure, n_temperature, target_ng
                )

                completed = output_index + 1
                if completed == 1 or completed % 100 == 0 or completed == target_nlam:
                    elapsed = time.monotonic() - start_time
                    print(
                        f"{completed:5d}/{target_nlam} bins "
                        f"({100.0 * completed / target_nlam:5.1f}%), "
                        f"elapsed {elapsed / 60.0:.1f} min",
                        flush=True,
                    )

            result.flush()

            primary_header = hdul[0].header.copy()
            primary_header["NLAM"] = target_nlam
            primary_header["NG"] = target_ng
            primary_header["L_MIN"] = float(target_lam[0])
            primary_header["L_MAX"] = float(target_lam[-1])
            primary_header.add_history(
                f"Wavelength k-distributions rebinned to R={resolution:g}"
            )

            output_hdus = fits.HDUList(
                [
                    fits.PrimaryHDU(data=result, header=primary_header),
                    fits.ImageHDU(
                        data=temperatures,
                        header=hdul[1].header.copy(),
                    ),
                    fits.ImageHDU(
                        data=pressures,
                        header=hdul[2].header.copy(),
                    ),
                    fits.ImageHDU(
                        data=target_lam,
                        header=hdul[3].header.copy(),
                    ),
                    fits.ImageHDU(data=target_g_weights),
                ]
            )
            output_hdus.writeto(output_path, overwrite=overwrite)
            output_hdus.close()
            del result

        elapsed = time.monotonic() - start_time
        print(f"Wrote {output_path} in {elapsed / 60.0:.1f} min")
    finally:
        if temp_path is not None and os.path.exists(temp_path):
            os.remove(temp_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Downsample an ARCiS correlated-k FITS file in wavelength"
    )
    parser.add_argument("input", type=Path, help="input ARCiS k-table")
    parser.add_argument("output", type=Path, help="output ARCiS k-table")
    parser.add_argument(
        "--resolution",
        "-R",
        type=float,
        default=1000.0,
        help="target wavelength resolving power (default: 1000)",
    )
    parser.add_argument(
        "--ng",
        type=int,
        default=25,
        help="target number of g points (default: 25, ARCiS default)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="replace an existing output file",
    )
    return parser.parse_args()


if __name__ == "__main__":
    arguments = parse_args()
    downsample(
        arguments.input,
        arguments.output,
        arguments.resolution,
        arguments.ng,
        arguments.overwrite,
    )
